### ISSUE TITLE
Allow writing `instance` more compactly

### ISSUE THREAD

**Issue by i-am-the-slime** [natefaubion/purescript-tidy#100]
Typeclass declarations in my code are already 95% boilerplate, so I'd very much like to keep them as compact as possible.
Tidy currently does a great job at dealing with derived instances, however:

```
derive instance Generic IntOrString _
derive instance Eq IntOrString
instance Show IntOrString where show = genericShow
instance ReadForeign IntOrString where readImpl = readGenericUntaggedSum
instance WriteForeign IntOrString where writeImpl = writeGenericUntaggedSum
```
turns into 
```
derive instance Generic IntOrString _
derive instance Eq IntOrString
instance Show IntOrString where
  show = genericShow

instance ReadForeign IntOrString where
  readImpl = readGenericUntaggedSum

instance WriteForeign IntOrString where
  writeImpl = writeGenericUntaggedSum
```

So it seems that as soon as there's a `where` tidy enforces the declaration to be multiline. 
Further it looks like it also enforces a newline after an instance declaration which makes it much more difficult to keep all instances for a given type visually close to each other.

I suggest that tidy leaves single-line instance declarations untouched (as long as they're not too wide) and that it doesn't enforce newlines after instances but keeps them if they're there.

**Comment by wclr** [comment]
I would prefer the lower sample, at least in this case, above code looks too dense anyway and not very pleasant.

**Comment by i-am-the-slime** [comment]
It becomes clearer when there are multiple ones:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/1588055/173223582-0955c988-dd89-4ae4-8b90-671a3f55d912.png">

vs.

<img width="508" alt="image" src="https://user-images.githubusercontent.com/1588055/173223631-1ef7f5cc-a1aa-4b70-aa23-41c3485153e3.png">

In the first example, I can very easily see where the types start and then all the instances are 99% noise anyway, so I want to be able to easily ski(p|m) them but it's important for me to see where a new type declaration starts.
That's easy in the first case.

**Comment by wclr** [comment]
On one hand that is a matter of visual preference (and taste) on the other, when I see a messy/overloaded form of code, I always expect a messy/overloaded essense of it.

**Comment by natefaubion** [comment]
I don't think we should allow single line where in instances because we don't allow single line where anywhere else there's a where, and that's not something I want to revisit in general. For me, this arguably falls into the bucket of "syntactic pun", where a particular formatting choice is made so that one thing evokes another thing. In this case it would be that you want the generic instances to look like the derived instances, because they feel like the same thing to you (and that's not unreasonable). I think it's likely that a future version of PS would support this style of instances declaration through deriving-via. If you feel strongly about less noise around instances like these, there's likely better long-term pay-off moving that forward. An alternative may be code folding instance declarations in your editor. I just don't think that tidy is the best way to solve this problem, though I appreciate that it's quicker to implement.

It's arguable that tidy should be inserting extra newlines at the top level. My personal opinion is that top-level multi-line declarations should always have extra spacing around them, and I think tidy does the job half-way right now by not inserting an extra newline after the deriving one-liners. This doesn't solve your problem of making instances more compact, but it would probably make it appear less irregular.

**Comment by i-am-the-slime** [comment]
I agree that the proper solution is to support a shorthand syntax à la `deriving (Eq, Ord, Show)` in Haskell. As a workaround I can at least visually group boring instances with some comments in between.
