### ISSUE TITLE
Large integers fail to parse

### ISSUE THREAD

**Issue by adrianroe** [natefaubion/purescript-tidy#37]
```purescript
module ReproLargeInt where

thresholdIntWorks :: Int
thresholdIntWorks = 2147483647

-- thresholdIntFails :: Int
-- thresholdIntFails = 2147483648

-- ourLargeIntFails :: Int
-- ourLargeIntFails = 9007199254740991

ourLargeFloatWorks :: Number
ourLargeFloatWorks = 9007199254740991.0
```

**Comment by kritzcreek** [comment]
These will fail with the compiler as well:
```
 Error 1 of 1

  Integer value 2147483648 is out of range for the JavaScript backend.
  Acceptable values fall within the range -2147483648 to 2147483647 (inclusive).
```

`Int` is a 32bit integer in PureScript, so you can't write literals larger than that.

**Comment by robashton** [comment]
> These will fail with the compiler as well:
> 
> ```
>  Error 1 of 1
> 
>   Integer value 2147483648 is out of range for the JavaScript backend.
>   Acceptable values fall within the range -2147483648 to 2147483647 (inclusive).
> ```
> 
> `Int` is a 32bit integer in PureScript, so you can't write literals larger than that.

Not in Erlang world

**Comment by adrianroe** [comment]
Sorry - should have said that code is from a Purerl project, so we have the luxury of supporting arbitrary sized integers...  The same happens with and without the type declaration.  Maybe it should read 
```purescript
thresholdIntFails :: MyErlangInt
thresholdIntFails = 2147483648
```
but you get the idea :). As Rob suggested, any questions of that nature to Nick!

And as in my post in Discord, huge huge thanks to all involved - the tool is wonderful and had almost no issues with 50k lines of our code.

**Comment by kritzcreek** [comment]
> Not in Erlang world*

Right, if we wanted to support this we'd have to parameterize [purescript-language-cst-parser](https://github.com/natefaubion/purescript-language-cst-parser), to allow larger(unbounded) literals.

I've checked and the Haskell CST implementation uses Haskell's `Integer` which is also unbounded.

I think it would be reasonable to support this in the PureScript implementation as well, though it'll be a little bit of a pain because JS BigInt's are less widely available than one might like.
