### ISSUE TITLE
Indent in data types

### ISSUE THREAD

**Issue by wclr** [natefaubion/purescript-tidy#78]
Tidy with indent 2 formats data record this way:
```purs
data User
  = UserA
      { name :: String
      , age :: Int
      , email :: String
      }
  | UserB
      { name :: String
      , age :: Int
      , email :: String
      }
```
So it st starts indenting from Name, not from operators (= or |), this seems _a bit discontinuous_ to me, won't it be more consistent to start from the operator?

```purs
data User
  = UserA
    { name :: String
    , age :: Int
    , email :: String
    }
  | UserB
    { name :: String
    , age :: Int
    , email :: String
    }
```

That is just an opinion, probably there is a good justification for implemented style.

**Comment by garyb** [comment]
I think this kind of discussion is exactly why Nate didn't want to write a formatter. 😄

To my eyes, especially in large chunks of code (like Halogen HTML, `case` with guards, etc.), the double-indented style makes the code much easier to scan due to the indentation structure being more obvious at a glance.

**Comment by wclr** [comment]
> I think this kind of discussion is exactly why Nate didn't want to write a formatter. 😄

I think any kind of discussion is appropriate if helps to explain and assert not obvious decisions made.

> the double-indented style 

It is not double-indented here btw, if the indent size is 4, then it will be 6 symbols away from the operator, not 8. For example [in this issue](https://github.com/natefaubion/purescript-tidy/issues/77)  we have a situation where we (probably) lack indentation.

**Comment by natefaubion** [comment]
Generally, with the start-of-line separators, we indent an extra 2-spaces to account for the separator and space, so that things appear indented past the leading identifier/expression. When scanning, the separator is ignored, and if you only have a single indent everything aligns on the same column making it more difficult to distinguish the various blocks.

```
data Foo
  = Foo
      ...
  | Bar
      ...
  | Baz
      ...

example =
  [ foo
      ...
  , bar
      ...
  , baz
      ...
  ]

example =
  { foo:
      ...
  , bar:
      ...
  , baz:
      ...
  }

-- No prefix separator, but indented past the identifier.
example = do
  let
    foo =
      ...
    bar =
      ...
    baz =
      ...
```

**Comment by wclr** [comment]
Right, I believe I buy it as a consistent style across different kinds of vertically separated things.
