### ISSUE TITLE
How does HangingDoc/FormatDoc work?

### ISSUE THREAD

**Issue by drathier** [natefaubion/purescript-tidy#95]
I've spent a couple of hours now poking around in the formatter, reading code, changing things around to see the effects on the tests, etc, but I don't feel like I have any understanding of the HangingDoc and FormatDoc types or their relation.

I tried to implement this: if the rhs of a case branch is multi-line, there should always be a newline after the `->`. If it's a one-liner, it can be left on the same line as the `->`.

Could you write a short intro to HangingDoc and FormatDoc? Or link to any existing docs?

**Comment by natefaubion** [comment]
> I tried to implement this: if the rhs of a case branch is multi-line, there should always be a newline after the ->. If it's a one-liner, it can be left on the same line as the ->.

Regardless of how it works, this is potentially a problematic rule. For example:

```purescript
example = case _ of
  Foo -> do
    let a = ...
    bar
```

This is multiline, and your rule would produce:
```purescript
example = case _ of
  Foo ->
    do
      let a = ...
      bar
```

Which I don't think is a commonly accepted style in use. One might say, well, we need to special-case `do` blocks. In reality, there's all sorts of common patterns that fit this rule which aren't necessarily do-blocks. For example, I frequently write code like this (and see it all over the place in the wild):

```purescript
example = SomeNewtype
  { foo: ...
  , bar: ...
  }
```

I also see operators like:

```purescript
example = foo $ bar
  { foo: ...
  , bar: ...
  }
```

`case` is another thing that's very commonly formatted like this. I call this "hanging". That is, there's some prefix that hangs onto the previous line before breaking in some way and indenting. `HangingDoc` is what encodes this rule and formatting behavior. The rule is fairly straightforward in concept. Something like: documents have an optional hanging prefix, and right associated prefixes are laid out horizontally before the suffix, which is then indented. Examples of hanging prefixes are:
* `do`/`ado`
* `case ... of`
* The RHS of an application
* The RHS and operator in a binary operator.

It gets really complicated though because I also wanted to encode dynamic page width layout. For example:

```purescript
example = foo $ bar $ SomeNewtype
  { ...
  }
```
Might get formatted as:
```purescript
example = foo
  $ bar
  $ SomeNewtype
      { ...
      }
```
Given a page width constraint. You also have to take into account operators of different precedence levels, and other weird chains, so it becomes its own tree layout routine.

I also try to treat case and algebraic pattern matching uniformly, so I don't see a different between `=` and `->` as far as what rules should be allowed. To me there's no difference between `example = ...`, `example (Foo a) = ...`, and `case _ of Foo a -> ...`, and they should all be formatted consistently, and so I think one should still be able to write the hanging prefixes like I mentioned.

I'd note it's somewhat ambiguous in the code generation case, but that would require additions to the dynamic behavior when there are no line break hints, and this distinction is largely blurred.

**Comment by drathier** [comment]
I think you've done an amazing job with those constraints in mind. One of those constraints is that different code bases can have different formatting styles, and another is that devs can format code to fit their local formatting needs. I'm currently seeing a lot of code at work that should be identical but isn't, i.e. the formatter allows to many different outputs for "the same" input, ignoring newlines. Thus, I'd much prefer this style:
```
example = 
  case _ of
    Foo ->
      do
        let a = ...
        bar
```
if the formatter was much more consistent about it. Removing the ability for individual devs to choose how code is formatted would help a lot. The more uniform the code is easier to read and review, and there's fewer points of discussion. That's why my first point of attack was this "always line break if multiline" rule, as this is the most common place for inconsistencies in our code base. Another common example is this:
```
example = thingy
  # perform
  # some
  # kind a b c
  # task
```
where I'd much rather have this:
```
example = 
  thingy
    # perform
    # some
    # kind a b c
    # task
```
I assume my design constrains are different from yours, but using a patched purescript-tidy seems to be a really useful way of reaching better code quality at work. If you want to take a look at the repo I'd be happy to invite you, but I highly doubt all changes we make would be useful to others, or of decent enough code quality that it would be useful to others. We've got a bunch of elm devs writing purescript at work, and they all praise https://github.com/avh4/elm-format precisely because it's so opinionated. The only real choice you have is if you want a short function to be multiline or not.

**Comment by natefaubion** [comment]
As an example:
https://github.com/natefaubion/purescript-tidy/blob/acb818ecbe14342a9057a8b0415cdb3fd772427b/src/Tidy.purs#L998

This is treating the `->` as the initial hanging prefix. Since you don't want hanging behavior at all, you could potentially do something like:
```purescript
 forkatToken conf tok `flexSpaceBreak` formatExpr conf expr
```

That is, use `formatExpr` instead, which flattens a HangingDoc into a FormatDoc, with `flexSpaceBreak` acting as either a space or break depending on with the expr is multiline.

**Comment by natefaubion** [comment]
If you find a lot of success with the tradeoffs, I'd be willing to look at making it an option like "no-hang" or something.

**Comment by drathier** [comment]
Amazing! I knew there would be an easy way to change this. First attempts look very promising!
