### ISSUE TITLE
One line row types closing/opening parens spacing

### ISSUE THREAD

**Issue by wclr** [natefaubion/purescript-tidy#99]
Row types doesn't use after/before spacing between closing/opening parens when it is one line:

```purs
type RowLine a = (name :: String, items :: Array (Something Int) | a)
```

If whe have multiline, we already have after/before spacing:

```
type RowLine a =
  ( name :: String
  , items :: Array (Something Int)
  | a
  )
```

Maybe it is appropriate to use spacing when row type placed in one line to distinct it from just parens used to group types, and be consisted with Record's `{` `}` that always have before/ater spacing and used to group fields as well:

```purs
type RowLine a = ( name :: String, items :: Array (Something Int) | a )
```

**Comment by natefaubion** [comment]
It is not clear to me that this is a problem. The current style is based on what is most often seen in the wild. I have seen `[...]` and `{...}` without spacing, but by far the most common has been spaces for squares and braces, and no spacing for parens. The latter arguably to a fault with regards to multi-line paren expressions. I made a decision to diverge with that because the alternative just does not scale well at all with arbitrarily large nesting. I do not want to make a choice like this which will affect everyone unless there's a really compelling reason.
